name: GitHub Actions Test1
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "starting the script"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: List s3 buckets in us-east-2 region
        run: |
          ls ${{ github.workspace }}/python
          python3 ${{ github.workspace }}/python/test.py
          aws s3 ls
      - run: echo "🍏 This job's status is ${{ job.status }}."
